name: Code Scanning to Jira Using API

on:
  push:
    branches: ["**"]
  # pull_request:
  #   branches: [main]
  #   types: [opened, reopened, synchronize, ready_for_review, labeled]

# on:
#   schedule:
#     - cron: '40 6 * * *' # 12:10 PM IST daily

jobs:
  codescanning-to-jira:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: read

    outputs:
      issue_found: ${{ steps.codescanning.outputs.issue_found }}
      rule_ids: ${{ steps.codescanning.outputs.rule_ids }}
      newrule_ids: ${{ steps.codescanning.outputs.newrule_ids }}

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: HylandSoftware/VulnerabilityToJIRATicket
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: VulnerabilityToJIRATicket

      - name: Check open Code Scanning alerts
        id: codescanning
        uses: ./VulnerabilityToJIRATicket/.github/actions/code-scanning-jira
        with:
          github_token: ${{ github.token }}
          jira_email: ${{ secrets.JIRA_USERS_EMAIL }}
          jira_api_token: ${{ secrets.JIRA_APIS_TOKEN }}
          jira_project: FCCCF
          jira_component: "Data Marshalling"

  create-jira:
    needs: codescanning-to-jira
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      security-events: read
    if: ${{ needs.codescanning-to-jira.outputs.issue_found == 'true' && needs.codescanning-to-jira.outputs.rule_ids != '[]' && needs.codescanning-to-jira.outputs.rule_ids != '' }}
    strategy:
      matrix:
        rule: ${{ fromJSON(needs.codescanning-to-jira.outputs.rule_ids) }}

    steps:

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          repository: HylandSoftware/VulnerabilityToJIRATicket
          ref: main
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: VulnerabilityToJIRATicket

      - name: Create Jira Ticket
        uses: ./VulnerabilityToJIRATicket/.github/actions/create-jira-tickets
        with:
          PROJECT_KEY: FCCCF
          COMPONENT: Data Marshalling
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BODY: |
            Security vulnerability detected for PR #${{ github.event.pull_request.number }}.

            Vulnerability: ${{ matrix.rule }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_APIS_TOKENS }}
          JIRA_EMAIL: ${{ secrets.JIRA_USERS_EMAIL }}
          ISSUE_TYPE: Bug
          LABELS: dependabot, untriaged, ${{ matrix.rule }}
